# Generated by Django 5.2.7 on 2026-01-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userfilesmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregistrationmodel",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
